const data = [
  {
    code: 200,
    msg: "성공하였습니다.",
    result: {
      mapListBanner: {
        bannerList: [],
        config: {
          isLoop: true,
          bannerExposureStartPoint: 3,
          bannerExposureGapCount: 10,
        },
      },
      roomList: [
        {
          seq: 52694280,
          id: "68ba7e8e89baeb422ca2c4c9",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.497282,
            lng: 126.729721,
          },
          complexName: "스카이씨티",
          roomTitle:
            "ㅇ부평시장역 인근ㅇ신축 첫입주ㅇ빠르게 없어지고있어요ㅇ인기쓰리룸ㅇ문e환영ㅇ",
          roomDesc: "저층, 77.22m², 관리비 8만",
          priceTypeName: "월세",
          priceTitle: "300/135",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/ldjjPGKt-d0VwcXwjtRYH",
            "https://d1774jszgerdmk.cloudfront.net/512/sItuz3rsZoS4FfvKSrlpX",
            "https://d1774jszgerdmk.cloudfront.net/512/YA_rBV3C9jYT_7Zx75BBN",
            "https://d1774jszgerdmk.cloudfront.net/512/QllNFRXablSXbJyLdGY1m",
            "https://d1774jszgerdmk.cloudfront.net/512/0cUH1gPkLiVKJuZS4W8Yu",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 49163815,
          id: "67bec76e032b2b12d53d0e0f",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.484733,
            lng: 126.723027,
          },
          complexName: "부평역해링턴플레이스",
          roomTitle:
            "2룸.최저가.냉장고.세탁기.에어컨.인덕션.넓은드레스룸.첫입주..전입불가",
          roomDesc: "고층, 59.94m², 관리비 확인 불가",
          priceTypeName: "월세",
          priceTitle: "2000/110",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/aUDSChmUmWyR9CmIyDeok",
            "https://d1774jszgerdmk.cloudfront.net/512/hkr-k68k4gjH7A8QXIS0s",
            "https://d1774jszgerdmk.cloudfront.net/512/F4Edpn9XAtixIRWnQaRUu",
            "https://d1774jszgerdmk.cloudfront.net/512/YrZKb3ojzC_6W8BfmWoQP",
            "https://d1774jszgerdmk.cloudfront.net/512/CQOMUnrRVgq4UuMcmWsgH",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52830620,
          id: "68c4dedb37a1c25a60523061",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.490749,
            lng: 126.727723,
          },
          complexName: "노블렌스",
          roomTitle:
            "실매물사진 빠른입주가능 전입신고가능 풀옵션복층형오피스텔",
          roomDesc: "중층, 20.96m², 관리비 10만",
          priceTypeName: "월세",
          priceTitle: "300/52",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/sl728OavphwYjG9iUu25L",
            "https://d1774jszgerdmk.cloudfront.net/512/Iv3ofLNkciA13Fpa2fIXg",
            "https://d1774jszgerdmk.cloudfront.net/512/JIrEhPoaT9Cy5JRTYHRx-",
            "https://d1774jszgerdmk.cloudfront.net/512/r-FK3vOZE-D3rAlIcfXpG",
            "https://d1774jszgerdmk.cloudfront.net/512/TaBk_g22QEZ48iT0oj7CW",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52953104,
          id: "68ce0f2b88a92d143a578ada",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.500584,
            lng: 126.722331,
          },
          complexName: "부평대우마이빌",
          roomTitle:
            "OㅅO 반려동물협의.수납 최고.큰방.오피스텔.구청역5분.빌트인",
          roomDesc: "15층, 32.57m², 관리비 9만",
          priceTypeName: "월세",
          priceTitle: "100/65",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/096d19f3-59d5-4196-9e5d-ecad3aa43c03",
            "https://d1774jszgerdmk.cloudfront.net/512/a7b6b754-0cc8-46af-8a9f-7536d08329e4",
            "https://d1774jszgerdmk.cloudfront.net/512/e54ba5d0-f891-4096-8681-1d55f2939a71",
            "https://d1774jszgerdmk.cloudfront.net/512/b6f7d5ad-bb23-4c5d-8656-379ae0729450",
            "https://d1774jszgerdmk.cloudfront.net/512/315f35cd-f626-49f2-8473-c5ac81160fdd",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52655109,
          id: "68b7f2e8c5d21f76734d188e",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.490749,
            lng: 126.727723,
          },
          complexName: "노블렌스",
          roomTitle: "ll 단기가능 ll 반려동물가능 ll 복층 ll 허위x ll",
          roomDesc: "10층, 19.8m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "80/48",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
            "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
            "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
            "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
            "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52623175,
          id: "68b64caff5a5663b98a6c5f8",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.489705,
            lng: 126.728623,
          },
          complexName: "부평현대더로프트",
          roomTitle: "NEW.부평대표복층/ 빌트인풀옵션/ 주차가능",
          roomDesc: "중층, 29.08m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "100/60",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/rEpI0hUe2Wb8R-iynOhuK",
            "https://d1774jszgerdmk.cloudfront.net/512/LzOWss0M7DbSBYrSczMJk",
            "https://d1774jszgerdmk.cloudfront.net/512/2UvcwNCGr32VzluWlOoDN",
            "https://d1774jszgerdmk.cloudfront.net/512/G7u5YNsXnsYBXdzP69cgY",
            "https://d1774jszgerdmk.cloudfront.net/512/w3R6_8HznuPqoTLWwS5mR",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52560673,
          id: "68b10d42de189d0f790ac58f",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.484733,
            lng: 126.723027,
          },
          complexName: "부평역해링턴플레이스",
          roomTitle: "전입안됨 투룸 풀옵션 첫입주 이사 아무때나",
          roomDesc: "고층, 59.94m², 관리비 확인 불가",
          priceTypeName: "월세",
          priceTitle: "2000/115",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/X9zELnzvHbxh3l3G_GwDg",
            "https://d1774jszgerdmk.cloudfront.net/512/Ao5jtE1_kIDLxSA_33sEY",
            "https://d1774jszgerdmk.cloudfront.net/512/87kjNs0NT5jXFrczxthLl",
            "https://d1774jszgerdmk.cloudfront.net/512/QjTC2uzFueDYzu6P26Bin",
            "https://d1774jszgerdmk.cloudfront.net/512/1s7OpqEos7sULBK93rjUR",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52887433,
          id: "68c9223e607f2371bc7d7cac",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.490846,
            lng: 126.722023,
          },
          complexName: "더시티뷰(생활숙박시설)",
          roomTitle: "ll 단기가능 ll 부평역1분 ll 신축 ll 허위x ll",
          roomDesc: "15층, 18.14m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "70/53",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/0yaxxxjC6w-eFa0swRhEc",
            "https://d1774jszgerdmk.cloudfront.net/512/fcMg8ck1oJ_oSa5UPNWxM",
            "https://d1774jszgerdmk.cloudfront.net/512/PZry3NMumT9Joo5Oso3K3",
            "https://d1774jszgerdmk.cloudfront.net/512/Nij7lrorSis4BQTnKGlli",
            "https://d1774jszgerdmk.cloudfront.net/512/3wH4Fb52DYw4YHASxg_dg",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52590710,
          id: "68b466ec57c801374efeea08",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.496674,
            lng: 126.729918,
          },
          complexName: "라일플로리스",
          roomTitle: "oo9월업데이트o단기o풀옵션oo저렴한방oo공실24시항시대기",
          roomDesc: "8층, 21.06m², 관리비 5만",
          priceTypeName: "월세",
          priceTitle: "60/47",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/rU0AER_u9UGc5uXNPyQkb",
            "https://d1774jszgerdmk.cloudfront.net/512/vEIEU34dU-4cM5DC5RcLj",
            "https://d1774jszgerdmk.cloudfront.net/512/jO6_EyMk3Fu7rfNEl2uw5",
            "https://d1774jszgerdmk.cloudfront.net/512/kLBnbydY7O2xYP_d3eg4a",
            "https://d1774jszgerdmk.cloudfront.net/512/chgllw7ZoGN_dUz-AGSOS",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52590720,
          id: "68b4676ecb5f6b3b2526d3e3",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.490846,
            lng: 126.722023,
          },
          complexName: "더시티뷰(생활숙박시설)",
          roomTitle: "oo9월업데이트o단기o풀옵션oo저렴한방oo공실24시항시대기",
          roomDesc: "7층, 18.14m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "70/53",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/Tj9f91ONUMVj5P-zgix-a",
            "https://d1774jszgerdmk.cloudfront.net/512/loMjNc0TUyDAn4ozw3bdu",
            "https://d1774jszgerdmk.cloudfront.net/512/KnpGzA-Y2cZNOsCgpTQf9",
            "https://d1774jszgerdmk.cloudfront.net/512/_SQV7ZYGID7xkZ5qFSqd-",
            "https://d1774jszgerdmk.cloudfront.net/512/4IkjxW-FsQZ1gQkkx0EDZ",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 48587837,
          id: "6794b0686cbd0f1fb454c2a3",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.484733,
            lng: 126.723027,
          },
          complexName: "부평역해링턴플레이스",
          roomTitle:
            "전입불가 .방2넓은거실.첫입주.풀옵션 동수역부평역도보가능대단지",
          roomDesc: "고층, 59.94m², 관리비 17만",
          priceTypeName: "월세",
          priceTitle: "2500/105",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/i7XeRBWIVnZCgiJMKmS_V",
            "https://d1774jszgerdmk.cloudfront.net/512/6E9-VaQMtBo8jrB4qvrjU",
            "https://d1774jszgerdmk.cloudfront.net/512/_wz-ca7HjQpWUNM3Sn1D5",
            "https://d1774jszgerdmk.cloudfront.net/512/2wMolBmiEyJuPUoAoDVCk",
            "https://d1774jszgerdmk.cloudfront.net/512/11wTFl1h9_2uO0xepu2Ik",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52799252,
          id: "68c2641b89876d175b1c999d",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.49799,
            lng: 126.723536,
          },
          complexName: "부평한라비발디",
          roomTitle:
            "단기가능,연장기능,신축풀옵션오피스텔,부평시장역초역세권,주차100",
          roomDesc: "중층, 22.26m², 관리비 8만",
          priceTypeName: "월세",
          priceTitle: "300/55",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/YLhlo0gPAhGjsLn_UYlug",
            "https://d1774jszgerdmk.cloudfront.net/512/eFjGVhkeLZH3i_MkhEcGk",
            "https://d1774jszgerdmk.cloudfront.net/512/xIKUbqGnkr_gfMib4hbkf",
            "https://d1774jszgerdmk.cloudfront.net/512/HtbgyQ9czIVhWyK9WfrYu",
            "https://d1774jszgerdmk.cloudfront.net/512/C2QFqhs_1snvuYSvDBpfJ",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52655096,
          id: "68b7f2d01420ac13701782f7",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.490749,
            lng: 126.727723,
          },
          complexName: "노블렌스",
          roomTitle: "ll 단기가능 ll 반려동물가능 ll 복층 ll 허위x ll",
          roomDesc: "10층, 19.8m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "80/48",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
            "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
            "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
            "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
            "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52574930,
          id: "68b24a27f5e00c0332f199e9",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.496674,
            lng: 126.729918,
          },
          complexName: "라일플로리스",
          roomTitle: "ll 단기가능 ll 가성비최고 ll 신축급 ll 즉시입주가능 ll",
          roomDesc: "7층, 19.71m², 관리비 5만",
          priceTypeName: "월세",
          priceTitle: "60/47",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/9eegI02RaPFObFdOF15ww",
            "https://d1774jszgerdmk.cloudfront.net/512/FJM7EVqYikn9zv_o3zbUG",
            "https://d1774jszgerdmk.cloudfront.net/512/b3-7zGMQPMb9kqA91Y-tU",
            "https://d1774jszgerdmk.cloudfront.net/512/9O7qpfE-pSKaBekvosUhn",
            "https://d1774jszgerdmk.cloudfront.net/512/sG26cUbwA6_PXH-cDC6wg",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52877868,
          id: "68c8ddfe9e1b72097e3676f5",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.501298,
            lng: 126.72329,
          },
          complexName: "카이저",
          roomTitle: "부평시장역 역세권 깔끔한3룸 풀옵션 월세입니다",
          roomDesc: "4층, 68.34m², 관리비 10.5만",
          priceTypeName: "월세",
          priceTitle: "1000/125",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/4VzSmIqi8u4iyxdR5kUd2",
            "https://d1774jszgerdmk.cloudfront.net/512/jW8Z1n-XT4G4KsHb5hZsO",
            "https://d1774jszgerdmk.cloudfront.net/512/LqxDPTqlQDSazk8VrS6zz",
            "https://d1774jszgerdmk.cloudfront.net/512/8-y1rR8QbY9aAI5Qwu3cZ",
            "https://d1774jszgerdmk.cloudfront.net/512/pav9ADIbX29Y5LNdWEKBh",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52563360,
          id: "68b120f7aebb4f799a91a167",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.490749,
            lng: 126.727723,
          },
          complexName: "노블렌스",
          roomTitle:
            "++단기가능,몸만입주하세요,깔끔컨디션,가성비끝판왕,쓰리역세권,풀옵션++",
          roomDesc: "10층, 19.8m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "80/48",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/AKWbyge7oOiyNe_MAhO8T",
            "https://d1774jszgerdmk.cloudfront.net/512/-5D189BsoIYFC-1kk5-_U",
            "https://d1774jszgerdmk.cloudfront.net/512/5MOedvwB_VE_F4nnNfKko",
            "https://d1774jszgerdmk.cloudfront.net/512/cGo2k5lN2MlVUZLD-AIPH",
            "https://d1774jszgerdmk.cloudfront.net/512/gXT1VHr_jvO6736GG4qSk",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52467953,
          id: "68aa7920c67adc7137c54be9",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.489705,
            lng: 126.728623,
          },
          complexName: "부평현대더로프트",
          roomTitle: "ll 단기가능 ll 부평역5분 ll 복층 ll 허위x ll",
          roomDesc: "8층, 23.25m², 관리비 5만",
          priceTypeName: "월세",
          priceTitle: "100/60",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/Fz6gLIU8JPcC38nyIqJVW",
            "https://d1774jszgerdmk.cloudfront.net/512/lfMpvWxo93YPFWYOzJNH9",
            "https://d1774jszgerdmk.cloudfront.net/512/HJ8P3uTN3s7ZcOjqHdWMa",
            "https://d1774jszgerdmk.cloudfront.net/512/k67ZmCm6e42EsJCsgVwpe",
            "https://d1774jszgerdmk.cloudfront.net/512/RG20A0gDockWnTjJthaUN",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52962280,
          id: "68ced2cb1727372512bd50ec",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.490294,
            lng: 126.719119,
          },
          complexName: "e편한세상시티부평역",
          roomTitle: "LHㅣ신축오피스텔ㅣ1.5룸ㅣ빌트인풀옵션",
          roomDesc: "17층, 27.09m², 관리비 8만",
          priceTypeName: "전세",
          priceTitle: "1억5000",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/eHkyRRql_G6xeLzt_Qfgd",
            "https://d1774jszgerdmk.cloudfront.net/512/lWDOW1aSGZPI_B9ag9_SM",
            "https://d1774jszgerdmk.cloudfront.net/512/gXn3mrFAX4Yxn1MOko9oF",
            "https://d1774jszgerdmk.cloudfront.net/512/vaDSKkv2I35v6Z36RkePJ",
            "https://d1774jszgerdmk.cloudfront.net/512/DrjL93htvACRcTIKzZUYf",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 51205361,
          id: "684d61602cc8a62811f841dc",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.490846,
            lng: 126.722023,
          },
          complexName: "더시티뷰(생활숙박시설)",
          roomTitle: "부평역바로앞.단기가능. 즉시입주.풀옵션",
          roomDesc: "6층, 18.14m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "70/53",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/o387yWqFj-CxsTpp6pQxn",
            "https://d1774jszgerdmk.cloudfront.net/512/CnaT-iuFeNT8MDizWXCrY",
            "https://d1774jszgerdmk.cloudfront.net/512/HRvkpi3YpyA1TAXL9V5CS",
            "https://d1774jszgerdmk.cloudfront.net/512/Mie67AkEt92GNVXrTwSpr",
            "https://d1774jszgerdmk.cloudfront.net/512/coxDyoUUUdtWy7XmZqeir",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52924348,
          id: "68cbab441c7bcc729545cee2",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.490749,
            lng: 126.727723,
          },
          complexName: "노블렌스",
          roomTitle: "부평역 5분거리에 있는 저렴한 복층 오피스텔",
          roomDesc: "4층, 19.8m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "300/42",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/9178d647-a56d-45a2-9d9b-7e43b41269ac",
            "https://d1774jszgerdmk.cloudfront.net/512/fb15445a-fd06-42fc-b77e-1e17d482e25a",
            "https://d1774jszgerdmk.cloudfront.net/512/8312c8c4-baa9-4d12-85a6-12dae41086bc",
            "https://d1774jszgerdmk.cloudfront.net/512/56062c0d-90d5-40ad-97d7-43692e214a6d",
            "https://d1774jszgerdmk.cloudfront.net/512/c2bd3bed-ffa8-44da-b583-45938c11b8b7",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52563369,
          id: "68b12107d6f8c8794b7a2184",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.490846,
            lng: 126.722023,
          },
          complexName: "더시티뷰(생활숙박시설)",
          roomTitle:
            "++단기가능,몸만입주하세요,깔끔컨디션,가성비끝판왕,쓰리역세권,풀옵션++",
          roomDesc: "7층, 18.14m², 관리비 7만",
          priceTypeName: "월세",
          priceTitle: "70/53",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/cqRnqO8CZq0WQO27_Mao5",
            "https://d1774jszgerdmk.cloudfront.net/512/ayZiWBeyGOF1DMTuox0wu",
            "https://d1774jszgerdmk.cloudfront.net/512/lhjDl0O8osCe13Jo5RDsi",
            "https://d1774jszgerdmk.cloudfront.net/512/xSywPWhm97lbJnwCBcvxy",
            "https://d1774jszgerdmk.cloudfront.net/512/1nYt4fMYYI98ujJR_RIbI",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52922751,
          id: "68cb9f088e7d074632401440",
          roomTypeName: "오피스텔",
          randomLocation: {
            lat: 37.489705,
            lng: 126.728623,
          },
          complexName: "부평현대더로프트",
          roomTitle: "급매 부평역5분 풀옵션복층 실입주가능",
          roomDesc: "10층, 28.48m², 관리비 8만",
          priceTypeName: "매매",
          priceTitle: "9300",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/CB6wvitPMnkm3ACdJrCXc",
            "https://d1774jszgerdmk.cloudfront.net/512/cfu3yz3xZw0RT34XYCeY1",
            "https://d1774jszgerdmk.cloudfront.net/512/e0QPW5kkOoh9eFLjCs5yK",
            "https://d1774jszgerdmk.cloudfront.net/512/KM6fmFrydGgNFQQkOyz4M",
            "https://d1774jszgerdmk.cloudfront.net/512/0tSm-ogVHiuqT9DyRpPTw",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52984323,
          id: "68d0e3f8f62a2a0895a05614",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.500584,
            lng: 126.722331,
          },
          complexName: "부평대우마이빌",
          roomTitle: "주차 한대 무료  넓고 수납공간 미친 풀옵션 원룸 단기임대",
          roomDesc: "6층, 32.57m², 관리비 9만",
          priceTypeName: "월세",
          priceTitle: "150/65",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/jGUADY2t2TNs9M5zZqb4d",
            "https://d1774jszgerdmk.cloudfront.net/512/aP9j1Jdm7uCn6HNrg2gV5",
            "https://d1774jszgerdmk.cloudfront.net/512/LWYBo8octfZprprT8CiRy",
            "https://d1774jszgerdmk.cloudfront.net/512/9aumaojWyHH68buXkDkAe",
            "https://d1774jszgerdmk.cloudfront.net/512/c9gnLQrb4obOIfoQzf2Fs",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
        {
          seq: 52574929,
          id: "68b24a1e74f9d307692a6d0f",
          roomTypeName: "오피스텔 • 단기",
          randomLocation: {
            lat: 37.496674,
            lng: 126.729918,
          },
          complexName: "라일플로리스",
          roomTitle: "ll 단기가능 ll 가성비최고 ll 신축급 ll 허위x ll",
          roomDesc: "8층, 21.06m², 관리비 5만",
          priceTypeName: "월세",
          priceTitle: "60/47",
          imgUrlList: [
            "https://d1774jszgerdmk.cloudfront.net/512/FJM7EVqYikn9zv_o3zbUG",
            "https://d1774jszgerdmk.cloudfront.net/512/b3-7zGMQPMb9kqA91Y-tU",
            "https://d1774jszgerdmk.cloudfront.net/512/9O7qpfE-pSKaBekvosUhn",
            "https://d1774jszgerdmk.cloudfront.net/512/9eegI02RaPFObFdOF15ww",
            "https://d1774jszgerdmk.cloudfront.net/512/sG26cUbwA6_PXH-cDC6wg",
          ],
          isExtendUI: true,
          isFavorite: false,
          isPano: false,
          isQuick: true,
          isDirect: false,
          isOwner: false,
          isOwnerAuth: false,
          isMyHome: false,
          isNaverVerify: false,
          formatNaverVerifyDate: null,
          isIconFocus: false,
          iconFocusType: null,
          gid: 9040,
          dongName: "부평동",
        },
      ],
      premiumList: [
        {
          roomList: [
            {
              seq: 52984323,
              id: "68d0e3f8f62a2a0895a05614",
              roomTypeName: "오피스텔 • 단기",
              randomLocation: {
                lat: 37.500584,
                lng: 126.722331,
              },
              complexName: "부평대우마이빌",
              roomTitle:
                "주차 한대 무료  넓고 수납공간 미친 풀옵션 원룸 단기임대",
              roomDesc: "6층, 32.57m², 관리비 9만",
              priceTypeName: "월세",
              priceTitle: "150/65",
              imgUrlList: [
                "https://d1774jszgerdmk.cloudfront.net/512/jGUADY2t2TNs9M5zZqb4d",
                "https://d1774jszgerdmk.cloudfront.net/512/aP9j1Jdm7uCn6HNrg2gV5",
                "https://d1774jszgerdmk.cloudfront.net/512/LWYBo8octfZprprT8CiRy",
                "https://d1774jszgerdmk.cloudfront.net/512/9aumaojWyHH68buXkDkAe",
                "https://d1774jszgerdmk.cloudfront.net/512/c9gnLQrb4obOIfoQzf2Fs",
              ],
              isFavorite: false,
              isPano: false,
              isIconFocus: false,
              iconFocusType: null,
              gid: 9040,
              dongName: "부평동",
            },
            {
              seq: 52904584,
              id: "68ca6d902e56ea6f4a6948e6",
              roomTypeName: "오피스텔 • 단기",
              randomLocation: {
                lat: 37.497282,
                lng: 126.729721,
              },
              complexName: "스카이씨티",
              roomTitle:
                "부평역 부평시장역 차로 4분거리 풀옵션 방3 화2 신축 첫입주 단기임대",
              roomDesc: "6층, 84.68m², 관리비 9만",
              priceTypeName: "월세",
              priceTitle: "300/125",
              imgUrlList: [
                "https://d1774jszgerdmk.cloudfront.net/512/mridBcCZ4myY-PQa7q214",
                "https://d1774jszgerdmk.cloudfront.net/512/5nSBvshq5EMoMi4Qs3T67",
                "https://d1774jszgerdmk.cloudfront.net/512/14Bf92_dTbFbq_kdOUM-Z",
                "https://d1774jszgerdmk.cloudfront.net/512/2VmtJI16YsUGoLmn4It5H",
                "https://d1774jszgerdmk.cloudfront.net/512/2WA7B9It5y6K7vmRUIcFp",
              ],
              isFavorite: false,
              isPano: false,
              isIconFocus: false,
              iconFocusType: null,
              gid: 9040,
              dongName: "부평동",
            },
          ],
          agent: {
            id: "677b3a2b5d76ba11352b6c6b",
            name: "엠씨티공인중개사사무소",
            profileUrl:
              "https://d2bqvyba2nre74.cloudfront.net/e493c5ba99dd38a9dffb41b3fd1f0000",
            activeRoomCount: 83,
            since: "2025.01.06",
          },
        },
        {
          roomList: [
            {
              seq: 51167720,
              id: "684a98de8c27195a0c9c9033",
              roomTypeName: "오피스텔 • 단기",
              randomLocation: {
                lat: 37.489705,
                lng: 126.728623,
              },
              complexName: "부평현대더로프트",
              roomTitle:
                "부평역2분 넓은복층 뻥뷰 최상컨디션 풀옵션 누구나 좋아할 초역세권",
              roomDesc: "고층, 44.25m², 관리비 7만",
              priceTypeName: "월세",
              priceTitle: "100/65",
              imgUrlList: [
                "https://d1774jszgerdmk.cloudfront.net/512/mL0kYCtiw8keFKu3Bumoe",
                "https://d1774jszgerdmk.cloudfront.net/512/SCuJCPWpvb9doPbxzXe2j",
                "https://d1774jszgerdmk.cloudfront.net/512/jH9V3h0Cw-OLuIzcHmh1x",
                "https://d1774jszgerdmk.cloudfront.net/512/QHraAzn114-U5U-Bosfuw",
                "https://d1774jszgerdmk.cloudfront.net/512/94DbGqYV1AB6CHPy5WNyz",
              ],
              isFavorite: false,
              isPano: false,
              isIconFocus: false,
              iconFocusType: null,
              gid: 9040,
              dongName: "부평동",
            },
            {
              seq: 51167825,
              id: "684a9bb2f146346e13b9ddbc",
              roomTypeName: "오피스텔 • 단기",
              randomLocation: {
                lat: 37.490516,
                lng: 126.730316,
              },
              complexName: "헤리움(힘찬헤리움)",
              roomTitle: "부평역5분 뷰맛집 최상급 풀옵션 대로변 살기 좋은집",
              roomDesc: "고층, 23.8m², 관리비 7만",
              priceTypeName: "월세",
              priceTitle: "80/52",
              imgUrlList: [
                "https://d1774jszgerdmk.cloudfront.net/512/NnXLOQeU_SNns7JlzpE1z",
                "https://d1774jszgerdmk.cloudfront.net/512/oNsITROV61aECbLfkm5NX",
                "https://d1774jszgerdmk.cloudfront.net/512/JoRmyNS3hW9X6X9gGCu30",
                "https://d1774jszgerdmk.cloudfront.net/512/bZvhqGBk9XNZ7bswuxn2q",
                "https://d1774jszgerdmk.cloudfront.net/512/_7Bu0FueOK2Zf-lcg58bt",
              ],
              isFavorite: false,
              isPano: false,
              isIconFocus: false,
              iconFocusType: null,
              gid: 9040,
              dongName: "부평동",
            },
          ],
          agent: {
            id: "68144fc74a68246e6ffc2988",
            name: "뉴골드공인중개사사무소",
            profileUrl:
              "https://d2bqvyba2nre74.cloudfront.net/7f7a5f6aa0a7090a85468726c625ce40",
            activeRoomCount: 150,
            since: "2025.05.02",
          },
        },
      ],
      region: null,
      total: 179,
      limit: 24,
      hasMore: true,
      page: 1,
    },
    responseTime: "2025-09-23 09:36:06",
  },
];

const newSection = document.createElement("section");
newSection.style.display = "flex";
newSection.style.flexDirection = "column";
newSection.style.width = 400 + "px";
document.body.appendChild(newSection);

data[0].result.roomList.forEach((v) => {
  const newArticle = document.createElement("article");
  newArticle.style.display = "flex";
  newArticle.style.flexDirection = "row";
  newArticle.style.alignItems = "center";
  newArticle.style.gap = "10px";
  newArticle.style.padding = "10px";
  newArticle.style.bordertop = "1px solid #dedede";
  newArticle.style.borderBottom = "1px solid #dedede";
  newSection.appendChild(newArticle);

  const photo = document.createElement("img");
  photo.src = v.imgUrlList[0];
  photo.style.objectFit = "cover";
  photo.style.width = 140 + "px";
  photo.style.height = 140 + "px";
  newArticle.appendChild(photo);

  const info = document.createElement("div");
  info.style.display = "flex";
  info.style.flexDirection = "column";
  newArticle.appendChild(info);

  const cost = document.createElement("h1");
  cost.innerText = v.priceTypeName + " " + v.priceTitle;
  cost.style.fontSize = "16px";
  info.appendChild(cost);

  const type = document.createElement("span");
  type.innerText = v.roomTypeName + v.complexName;
  type.style.fontSize = "14px";
  type.style.color = "#5c5c5c";
  info.appendChild(type);

  const type2 = document.createElement("span");
  type2.innerText = v.roomDesc;
  type2.style.fontSize = "13px";
  type2.style.color = "#5c5c5c";
  info.appendChild(type2);

  const type3 = document.createElement("span");
  type3.innerText = v.roomTitle;
  type3.style.fontSize = "12px";
  type3.style.color = "#5c5c5c";
  type3.style.marginbottom = "25px";
  info.appendChild(type3);

  const btn = document.createElement("button");
  btn.innerText = "플러스";
  btn.style.width = "60px";
  btn.style.fontSize = "12px";
  btn.style.color = "#243cf2";
  btn.style.backgroundcolor = "#d1cfcf";
  btn.style.margin = "10px 0";
  btn.style.border = "none";
  btn.style.borderRadius = "2px";

  info.appendChild(btn);
});

/*
  type.style.testOverflow = ellipsis;
  type.style.whiteSpace = nowrap;
  type.style.overflow = hidden;
*/
